name: coursehub
description: Online E-Learning App
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.1.1
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  modal_progress_hud: ^0.1.3

  # responsive ui test
  device_preview: ^1.1.0

  # responsive text font
  auto_size_text: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  cloud_firestore: ^3.5.1
  http: ^0.13.5
  google_sign_in: ^5.4.2
  velocity_x: ^3.6.0
  connectivity: ^3.0.6
  fluttertoast: ^8.0.9
  share: ^2.0.4
  youtube_player_iframe: ^3.1.0
  youtube_player_flutter: ^8.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Light.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages